### ISSUE TITLE
IE8: Invalid Argument

### ISSUE THREAD

**Issue by splintercode** [10up/flexibility#34]
I have replicated the issue with this case https://github.com/10up/flexibility/issues/23

The bug is when there is a negative value in the selected property it throws. I have a class in my css grid as below. The margin with a negative value causes the error. If I make it a positive value the error goes away. Ill try to get a demo up as well. 

``` scss
.flex-row--gutter-between-none  {
    -webkit-flex-wrap: wrap;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    -js-display: flex;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    margin-left: -8px;     // <- causes error
    margin-right: -8px;   // <- causes error
}
```
