### ISSUE TITLE
Not Working on IE9

### ISSUE THREAD

**Issue by cjkoepke** [10up/flexibility#35]
Hey guys,

First, thank you for making this plugin. Seriously, not having to setup a fallback is music to my ears—that is, if I can get it to work.

To the best of my knowledge, there's no reason this shouldn't be working, but it doesn't seem to be honoring any changes I make to flexbox declarations.

This is suppose to be a grid system. In Chrome, it looks like this:

<img width="1385" alt="screen shot 2016-02-09 at 11 32 17 am" src="https://cloud.githubusercontent.com/assets/2815568/12926476/cf8f8e7c-cf20-11e5-9d4c-157d861c2796.png">

But in IE9, it looks like this:

<img width="776" alt="screen shot 2016-02-09 at 11 28 27 am" src="https://cloud.githubusercontent.com/assets/2815568/12926409/8c53d528-cf20-11e5-9a9d-fe1d3c0b4f11.png">

The relevant code is as follows:

### Markup
```html
<div class="grid">
	<div class="grid-box">
		<a class="grid-box-content" href="#">
			<span class="icon-tool-box"></span>
			<h3 class="grid-box-title">Title</h3>
			<p>Body Content</p>
		</a>
	</div><!-- end .grid-box -->
	<div class="grid-box">
		<a class="grid-box-content" href="#">
			<span class="icon-tool-box"></span>
			<h3 class="grid-box-title">Title</h3>
			<p>Body Content</p>
		</a>
	</div><!-- end .grid-box -->
        <div class="grid-box">
		<a class="grid-box-content" href="#">
			<span class="icon-tool-box"></span>
			<h3 class="grid-box-title">Title</h3>
			<p>Body Content</p>
		</a>
	</div><!-- end .grid-box -->	
</div>
```

### CSS
```css
.grid {
    -js-display: flex;
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: horizontal;
    -webkit-box-direction: normal;
    -webkit-flex-direction: row;
    -ms-flex-direction: row;
    flex-direction: row;
    -webkit-box-align: stretch;
    -webkit-align-items: stretch;
    -ms-flex-align: stretch;
    align-items: stretch;
    -webkit-flex-wrap: wrap;
    -ms-flex-wrap: wrap;
    flex-wrap: wrap;
    overflow: visible;
    width: 100%;
}

.grid-box {
    background-color: #fff;
    border: 1px solid #eee;
    border-width: 0 1px 1px 0;
    color: #222;
    margin: 0;
    vertical-align: top;
    width: 33.333333333333%;
    -js-display: flex;
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: stretch;
    -webkit-align-items: stretch;
    -ms-flex-align: stretch;
    align-items: stretch;
    height: auto;
}

.grid-box-content {
    -js-display: flex;
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-orient: vertical;
    -webkit-box-direction: normal;
    -webkit-flex-direction: column;
    -ms-flex-direction: column;
    flex-direction: column;
    -webkit-box-pack: justify;
    -webkit-justify-content: flex-start;
    -ms-flex-pack: justify;
    justify-content: flex-start;
    min-height: 0;
    overflow: hidden;
    padding: 50px;
    width: 100%;
}
```

I'm hoping I'm just doing something wrong. Any help would be greatly appreciated, thank you!
