### ISSUE TITLE
Width calculation in combination with :last-child and margin IE9/IE10

### ISSUE THREAD

**Issue by TwR-Slice** [10up/flexibility#37]
Hi,

i think there is a miscalculation of the :last-child elements width.
The SCSS:
```css
.container{
            -js-display: flex;
            display: -webkit-box;
            display: -webkit-flex;
            display: -moz-box;
            display: -ms-flexbox;
            display: flex;

            .item{
                width: 20%;
                margin-right: 9px;
                -webkit-flex-shrink: 1;
                -ms-flex-negative: 1;
                flex-shrink: 1;
                -webkit-flex-basis: auto;
                -ms-flex-preferred-size: auto;
                flex-basis: auto;
                -webkit-box-flex: 1;
                -webkit-flex-grow: 1;
                -moz-box-flex: 1;
                -ms-flex-positive: 1;
                flex-grow: 1;

                &:last-child {
                    margin-right: 0;
                }
            }
}

```
The HTML (simplified):
```html
<div class="container">
    <input class="item">
    <input class="item">
    <input class="item">
    <input class="item">
</div>
```
It seems that the last element is calculated with its margin still active.

Chrome 48.0:
![bildschirmfoto 2016-02-18 um 12 14 40](https://cloud.githubusercontent.com/assets/14914344/13141833/c46ad572-d639-11e5-84b3-4987145ed047.png)

IE9 & IE10 (IE8 untested)
![bildschirmfoto 2016-02-18 um 12 06 53](https://cloud.githubusercontent.com/assets/14914344/13141852/d9b97c80-d639-11e5-9996-192dacd3969c.png)

It's not a major problem for my current projects as older IEs are not fully supported but maybe it helps.

Greetings,
Robert
